import { ArrowRight, BarChart3, ShieldCheck, Swords } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { Card, LinkButton } from "@/components/ui";

export default function HomePage() {
  return <main className="mx-auto flex min-h-screen max-w-7xl flex-col px-5 py-6 sm:px-8 lg:px-12">
    <nav className="flex items-center justify-between"><div className="flex items-center gap-3"><BrandMark className="size-11" /><div><p className="font-display text-lg font-semibold">EDH Pod Tracker</p><p className="text-[10px] tracking-[.18em] text-stone-500 uppercase">Playgroup ledger</p></div></div><LinkButton href="/login" variant="secondary">Sign in</LinkButton></nav>
    <section className="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
      <div className="enter"><p className="mb-5 text-xs font-bold tracking-[.22em] text-amber-300 uppercase">Every pod tells a story</p><h1 className="font-display max-w-3xl text-5xl leading-[.95] font-semibold tracking-[-.04em] text-white sm:text-6xl lg:text-7xl">Remember more than who won.</h1><p className="mt-7 max-w-xl text-base leading-7 text-stone-400 sm:text-lg">Track decks, games, achievements, rivalries, and the delightful nonsense that makes your Commander table yours.</p><div className="mt-8 flex flex-wrap gap-3"><LinkButton href="/login">Open your table <ArrowRight className="size-4" /></LinkButton><LinkButton href="#features" variant="ghost">See what’s tracked</LinkButton></div></div>
      <Card className="enter relative overflow-hidden p-5 sm:p-7"><div className="absolute -top-24 -right-24 size-64 rounded-full bg-violet-700/20 blur-3xl" /><div className="relative"><div className="mb-7 flex items-start justify-between"><div><p className="text-xs font-bold tracking-[.16em] text-stone-500 uppercase">The Sunday Pod</p><p className="font-display mt-1 text-2xl">Season snapshot</p></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/10 px-3 py-1 text-xs font-semibold text-emerald-200">24 games</span></div><div className="grid grid-cols-3 gap-2"><Metric value="31%" label="Top win rate" /><Metric value="18" label="Active decks" /><Metric value="42" label="Achievements" /></div><div className="mt-6 space-y-3"><PlayerRow name="Mara" deck="Alela, Artful Provocateur" wins={7} tone="bg-violet-400" /><PlayerRow name="Nico" deck="Krenko, Mob Boss" wins={6} tone="bg-red-400" /><PlayerRow name="Santi" deck="Muldrotha, the Gravetide" wins={5} tone="bg-emerald-400" /></div></div></Card>
    </section>
    <section id="features" className="grid gap-3 pb-14 md:grid-cols-3"><Feature icon={<Swords />} title="Fast game entry" copy="Choose the table, decks, and winner. History-safe snapshots handle the rest." /><Feature icon={<BarChart3 />} title="Useful metrics" copy="See form, rivalries, deck performance, brackets, and participation without spreadsheet formulas." /><Feature icon={<ShieldCheck />} title="Private by design" copy="POD roles and database policies keep every playgroup’s data inside its own table." /></section>
  </main>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-white/8 bg-white/5 p-3"><p className="font-display text-2xl text-white">{value}</p><p className="mt-1 text-[10px] tracking-wide text-stone-500 uppercase">{label}</p></div>; }
function PlayerRow({ name, deck, wins, tone }: { name: string; deck: string; wins: number; tone: string }) { return <div className="flex items-center gap-3 rounded-xl border border-white/7 bg-black/20 p-3"><span className={`size-2 rounded-full ${tone}`} /><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-white">{name}</p><p className="truncate text-xs text-stone-500">{deck}</p></div><span className="text-xs font-semibold text-stone-300">{wins} wins</span></div>; }
function Feature({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <Card className="p-5"><div className="mb-4 grid size-10 place-items-center rounded-xl bg-amber-300/10 text-amber-200 [&>svg]:size-5">{icon}</div><h2 className="font-display text-xl">{title}</h2><p className="mt-2 text-sm leading-6 text-stone-400">{copy}</p></Card>; }
