"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Check, LockKeyhole } from "lucide-react";
import { ApiClientError, apiRequest } from "@/lib/client-api";
import { Badge, Card } from "@/components/ui";

type Catalog = { id: string; name: string; category: string; description: string; archivedAt: Date | string | null };
type Member = { id: string; displayName: string };
type Grant = { playerId: string; achievementId: string; revokedAt: Date | string | null; version: number; grantedAt: Date | string; grantedByName: string; notes: string };

export function AchievementMatrix({ podId, catalog, members, grants, canEdit }: { podId: string; catalog: Catalog[]; members: Member[]; grants: Grant[]; canEdit: boolean }) {
  const router = useRouter(); const [pending, setPending] = useState<string>(); const [error, setError] = useState<string>(); const [category, setCategory] = useState("All"); const [player, setPlayer] = useState("All"); const [earned, setEarned] = useState("All"); const [catalogState, setCatalogState] = useState("Active"); const [note, setNote] = useState("");
  const categories = ["All", ...new Set(catalog.map((item) => item.category))];
  const activeGrant = (playerId: string, achievementId: string) => grants.find((grant) => grant.playerId === playerId && grant.achievementId === achievementId && !grant.revokedAt);
  const visibleMembers = player === "All" ? members : members.filter((member) => member.id === player);
  const visible = catalog.filter((item) => {
    if (category !== "All" && item.category !== category) return false;
    if (catalogState === "Active" && item.archivedAt) return false;
    if (catalogState === "Archived" && !item.archivedAt) return false;
    if (earned === "All") return true;
    const relevantPlayers = player === "All" ? members : visibleMembers;
    const hasGrant = relevantPlayers.some((member) => activeGrant(member.id, item.id));
    return earned === "Earned" ? hasGrant : !hasGrant;
  });
  async function toggle(playerId: string, achievementId: string) { const item = catalog.find((candidate) => candidate.id === achievementId); if (item?.archivedAt) return; const key = `${playerId}:${achievementId}`; setPending(key); setError(undefined); const grant = activeGrant(playerId, achievementId); try { await apiRequest(`/api/v1/pods/${podId}/achievement-grants`, grant ? { method: "DELETE", body: JSON.stringify({ playerId, achievementId, version: grant.version }) } : { method: "POST", body: JSON.stringify({ playerId, achievementId, notes: note }) }); if (!grant) setNote(""); router.refresh(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "Achievement update failed."); } finally { setPending(undefined); } }
  return <div className="grid gap-5"><div className="flex gap-2 overflow-x-auto">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 rounded-full border px-3 py-1.5 text-xs font-semibold ${category === item ? "border-amber-300/30 bg-amber-300/12 text-amber-200" : "border-white/8 text-stone-500 hover:text-white"}`}>{item}</button>)}</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><select aria-label="Filter player" value={player} onChange={(event) => setPlayer(event.target.value)} className="h-10 rounded-xl border border-white/10 bg-stone-950 px-3 text-sm"><option value="All">All players</option>{members.map((member) => <option key={member.id} value={member.id}>{member.displayName}</option>)}</select><select aria-label="Filter earned status" value={earned} onChange={(event) => setEarned(event.target.value)} className="h-10 rounded-xl border border-white/10 bg-stone-950 px-3 text-sm"><option>All</option><option>Earned</option><option>Unearned</option></select><select aria-label="Filter catalog status" value={catalogState} onChange={(event) => setCatalogState(event.target.value)} className="h-10 rounded-xl border border-white/10 bg-stone-950 px-3 text-sm"><option>Active</option><option>Archived</option><option>All</option></select><input aria-label="Optional note for the next grant" value={note} onChange={(event) => setNote(event.target.value)} maxLength={500} placeholder="Optional grant note" className="h-10 rounded-xl border border-white/10 bg-stone-950 px-3 text-sm" /></div>{error && <p role="alert" className="text-sm text-red-300">{error}</p>}
    <Card className="hidden overflow-auto md:block"><table className="w-full min-w-[720px] border-collapse text-left"><thead><tr className="border-b border-white/8"><th className="sticky left-0 z-10 bg-stone-950 p-4 text-xs tracking-[.14em] text-stone-500 uppercase">Player</th>{visible.map((item) => <th key={item.id} className="max-w-40 p-4 text-xs font-semibold text-stone-300"><span title={item.description}>{item.name}{item.archivedAt ? " · archived" : ""}</span></th>)}</tr></thead><tbody>{visibleMembers.map((member) => <tr key={member.id} className="border-b border-white/6 last:border-0"><th className="sticky left-0 bg-stone-950 p-4 text-sm font-semibold">{member.displayName}</th>{visible.map((item) => { const grant = activeGrant(member.id, item.id); const isEarned = Boolean(grant); const key = `${member.id}:${item.id}`; return <td key={item.id} className="p-4"><button title={grant ? `Granted by ${grant.grantedByName} on ${new Date(grant.grantedAt).toLocaleDateString()}${grant.notes ? ` · ${grant.notes}` : ""}` : undefined} disabled={!canEdit || Boolean(item.archivedAt) || pending === key} onClick={() => toggle(member.id, item.id)} aria-label={`${isEarned ? "Revoke" : "Grant"} ${item.name} for ${member.displayName}`} className={`grid size-9 place-items-center rounded-full border transition ${isEarned ? "border-emerald-300/25 bg-emerald-300/12 text-emerald-200" : "border-white/10 text-stone-700 hover:border-amber-300/25 hover:text-amber-200"}`}>{isEarned ? <Check className="size-4" /> : canEdit && !item.archivedAt ? "·" : <LockKeyhole className="size-3" />}</button></td>; })}</tr>)}</tbody></table></Card>
    <div className="grid gap-4 md:hidden">{visibleMembers.map((member) => <Card key={member.id} className="p-4"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl">{member.displayName}</h2><Badge tone="green">{visible.filter((item) => activeGrant(member.id, item.id)).length} / {visible.length}</Badge></div><div className="grid gap-2">{visible.map((item) => { const grant = activeGrant(member.id, item.id); const isEarned = Boolean(grant); return <button key={item.id} disabled={!canEdit || Boolean(item.archivedAt)} onClick={() => toggle(member.id, item.id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${isEarned ? "border-emerald-300/20 bg-emerald-300/8" : "border-white/7"}`}><span className={`grid size-7 place-items-center rounded-full ${isEarned ? "bg-emerald-300/15 text-emerald-200" : "bg-white/5 text-stone-700"}`}>{isEarned && <Check className="size-3.5" />}</span><span><span className="block text-sm font-semibold">{item.name}{item.archivedAt ? " · archived" : ""}</span><span className="text-xs text-stone-500">{grant ? `Granted by ${grant.grantedByName} on ${new Date(grant.grantedAt).toLocaleDateString()}${grant.notes ? ` · ${grant.notes}` : ""}` : item.description}</span></span></button>; })}</div></Card>)}</div>
  </div>;
}
